# Example configuration file for YNAB Transaction Updater
# Copy this file to config.yml and update with your actual values

# YNAB Configuration
ynab:
  api_key: "your_actual_ynab_api_key_here"  # Get from https://app.youneedabudget.com/settings/developer
  budget_id: "your_actual_ynab_budget_id_here"    # Found in YNAB URL when viewing budget or using the API
  base_url: "https://api.ynab.com/v1"

# Amazon Configuration
amazon:
  # Email-based order fetching (recommended if you want automatic import):
  # Note: Email fetching now automatically includes Subscribe & Save delivery notifications
  email: "your_amazon_email@example.com"  # Your Amazon email address (IMAP, e.g. Gmail)
  email_password: "your_amazon_email_app_password"  # App password for your Amazon email (use an app password, not your main password)
  # Optional: If Subscribe & Save emails are forwarded from another account
  # forward_from_address: "some.email@example.com"  # Email address that forwards S&S emails to your inbox
  # IMAP Configuration (optional, defaults to Gmail)
  # imap_host: "imap.gmail.com"  # IMAP server hostname (default: imap.gmail.com)
  # imap_port: 993  # IMAP server port (default: 993)
  # CSV fallback (if email fetching is not used or fails):
  csv_file_path: "amazon_orders.csv"  # Your exported Amazon order history CSV file

# Walmart Configuration (optional)
walmart:
  enabled: false  # Set to true to enable Walmart order fetching
  mode: "guest"  # Mode: "guest" (email lookup) or "login" (requires password) (default: "guest")
  email: "your_email@example.com"  # Email address to search for Walmart order notifications (IMAP, e.g. Gmail)
  walmart_email: "your_walmart_account@example.com"  # Actual Walmart account email. Might be same as `email` but might be different. If not specified, defaults to `email`
  email_password: "your_email_app_password"  # Email app password for IMAP access (required for guest mode)
  password: "your_walmart_password"  # Your Walmart account password (required only for login mode)
  # Optional: If Walmart emails are forwarded from another account
  # forward_from_address: "some.email@example.com"  # Email address that forwards Walmart emails to your inbox (guest mode only)
  # IMAP Configuration (optional, defaults to Amazon IMAP settings if not specified)
  # imap_host: "imap.gmail.com"  # IMAP server hostname (defaults to amazon.imap_host)
  # imap_port: 993  # IMAP server port (defaults to amazon.imap_port)
  headless: true  # Set to false to see browser in action (optional, default: true)
  browser_timeout: 30000  # Browser operation timeout in milliseconds (optional, default: 30000)
  orders_url: "https://www.walmart.com/orders"  # Walmart orders URL (optional, default shown)

# Application Configuration
app:
  look_back_days: 30  # Number of days to look back for transactions
  processed_transactions_file: "processed_transactions.json"  # Tracks which transactions have been processed
  log_level: "INFO"  # Options: DEBUG, INFO, WARN, ERROR
  dry_run: true  # Set to false when ready to make actual changes to YNAB

# ---
# Property documentation:
# amazon.email: Email address to fetch Amazon order confirmations from (IMAP required)
#               Automatically includes Subscribe & Save delivery notifications
# amazon.email_password: App password for the above email (never use your main password)
# amazon.forward_from_address: Optional - Email address you forward S&S emails from (if applicable)
# amazon.imap_host: IMAP server hostname (optional, default: imap.gmail.com)
# amazon.imap_port: IMAP server port (optional, default: 993)
# amazon.csv_file_path: Path to your Amazon order CSV file (used as fallback)
# walmart.enabled: Enable/disable Walmart order fetching (default: false)
# walmart.mode: Mode to use - "guest" (email lookup) or "login" (account login) (default: "guest")
# walmart.email: Email address to search for Walmart order notifications (IMAP). If only one email specified, used for both.
# walmart.walmart_email: Actual Walmart account email (used in order lookup form). If only one email specified, used for both.
# walmart.email_password: Email app password for IMAP access (required for guest mode)
# walmart.password: Your Walmart account password (required only for login mode)
# walmart.forward_from_address: Optional - Email address you forward Walmart emails from (guest mode only, if applicable)
# walmart.imap_host: IMAP server hostname (optional, defaults to amazon.imap_host)
# walmart.imap_port: IMAP server port (optional, defaults to amazon.imap_port)
# walmart.headless: Run browser in headless mode (default: true, set to false to see browser in action)
# walmart.browser_timeout: Timeout for browser operations in milliseconds (optional, default: 30000)
# walmart.orders_url: URL for Walmart orders page (optional, default: https://www.walmart.com/orders)

# Example of what your actual config.yml should look like:
# ynab:
#   api_key: "sk_prod_1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
#   account_id: "12345678-1234-1234-1234-123456789012"
#   base_url: "https://api.ynab.com/v1"
# 
# amazon:
#   email: "your.email@example.com"
#   csv_file_path: "my_amazon_orders.csv"
# 
# walmart:
#   enabled: true
#   mode: "guest"  # Use guest mode for email lookup (no Walmart password needed)
#   email: "your.email@example.com"  # Email to search for Walmart notifications
#   walmart_email: "your.walmart.account@example.com"  # Walmart account email (defaults to `email` if not specified)
#   email_password: "your_email_app_password"  # Email app password for guest mode
#   # password: "your_secure_walmart_password"  # Only needed if using mode: "login"
#   headless: false  # Set to false to see browser in action while testing
# 
# app:
#   processed_transactions_file: "processed_transactions.json"
#   log_level: "INFO"
#   dry_run: false 